package HealthProtocol.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int EvaluationEntry = 0;
  public static final int InputSpec = 1;
  public static final int Measurement = 2;
  public static final int ProtocolUK = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe2cc6d8e4cb94ceaL, 0xb8541f40eeed620dL);
    builder.put(0x38aa4973783632efL, EvaluationEntry);
    builder.put(0x38aa4973783632eeL, InputSpec);
    builder.put(0x38aa4973783632f0L, Measurement);
    builder.put(0x38aa4973783632e8L, ProtocolUK);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
